sonar.projectKey=sqp_40c49a58208822757d936ec6b3059e589709f73e
sonar.projectName=locally_001
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=java   # change if needed

sonar.sourceEncoding=UTF-8